services:
  fluent-bit:
    container_name: fluent-bit
    restart: unless-stopped
    image: fluent/fluent-bit:5.0.2-amd64
    volumes:
      - ./fluent-bit.yaml:/fluent-bit/etc/fluent-bit.yaml
    configs:
      - source: fluent-bit
        target: /fluent-bit/etc/fluent-bit.yaml
    environment:
      - AXIOM_TOKEN=${AXIOM_TOKEN}
      - AXIOM_DATASET_NAME=${AXIOM_DATASET_NAME}
      - AXIOM_REGION=${AXIOM_REGION}
    networks:
      - docker-proxy-net
      - public-net
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: 128M
    healthcheck:
      test: wget --spider http://127.0.0.1:2020/api/v2/health || exit 1
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 20s
    depends_on:
      docker-proxy:
        condition: service_healthy
