services:
  docker-proxy:
    container_name: docker-proxy
    restart: unless-stopped
    image: tecnativa/docker-socket-proxy:v0.4.2
    environment:
      - CONTAINERS=1
    networks:
      - docker-proxy-net
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: 32M
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget --quiet --spider http://docker-proxy:2375/version || exit 1",
        ]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 20s
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  traefik:
    container_name: traefik
    restart: unless-stopped
    image: traefik:v3.6.14
    command:
      - "--ping=true"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:${ENTRYPOINT_PORT}"
      - "--providers.docker.endpoint=tcp://docker-proxy:2375"
      - "--providers.docker.exposedbydefault=false"
    networks:
      - public-net
      - vpn-net
      - docker-proxy-net
      - fastapi-net
    ports:
      - ${ENTRYPOINT_PORT}:${ENTRYPOINT_PORT}
      - 10.66.66.1:8080:8080
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: 128M
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget --quiet --spider http://127.0.0.1:8080/ping || exit 1",
        ]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 20s
    depends_on:
      docker-proxy:
        condition: service_healthy
