services:
  postgredb:
    container_name: postgredb
    restart: unless-stopped
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST_AUTH_METHOD: md5
      POSTGRES_INITDB_ARGS: --auth=md5
    networks:
      - fastapi-net
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 1024M
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready",
          "-d",
          "-U",
          "${POSTGRES_USER}",
          "${POSTGRES_DB}",
        ]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 20s

  pgbouncer:
    container_name: pgbouncer
    restart: unless-stopped
    image: edoburu/pgbouncer:v1.25.1-p0
    environment:
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_HOST: ${POSTGRES_HOST}
      DB_NAME: ${POSTGRES_DB}
      ADMIN_USERS: postgres,admin
      POOL_MODE: transaction
      MAX_CLIENT_CONN: 1000
      DEFAULT_POOL_SIZE: 90
    networks:
      - fastapi-net
    ports: 
      - ${PG_BOUNCER_PORT}:${PG_BOUNCER_PORT}
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: 64M
    healthcheck:
      test: ["CMD", "pg_isready", "-h", "${POSTGRES_HOST}"]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 20s
    depends_on:
      postgredb:
        condition: service_healthy

  redis:
    container_name: redis
    restart: unless-stopped
    image: redis:7-alpine
    networks:
      - fastapi-net
    ports: 
      - ${REDIS_PORT}:${REDIS_PORT}
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: 512M
    healthcheck:
      test: ["CMD-SHELL", "redis-cli", "ping"]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 20s

  adminer:
    container_name: adminer
    restart: unless-stopped
    image: adminer:5.4.2-standalone
    environment:
      ADMINER_DEFAULT_SERVER: pgbouncer
      ADMINER_DEFAULT_SYSTEM: pgsql
    networks:
      - fastapi-net
    ports:
      - 8081:8080
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: 64M
    depends_on:
      pgbouncer:
        condition: service_healthy
      postgredb:
        condition: service_healthy

  vector:
    container_name: vector
    restart: unless-stopped
    image: timberio/vector:0.54.0-alpine
    environment:
      - VECTOR_CONFIG=/etc/vector/vector_dev.toml
    networks:
      - fastapi-net
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: 128M
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget --quiet --spider http://127.0.0.1:8686/health || exit 1",
        ]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 20s
    volumes:
      - ./vector_dev.toml:/etc/vector/vector_dev.toml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro

networks:
  fastapi-net:
    name: fastapi-net
