services:
  cadvisor:
    container_name: cadvisor
    restart: unless-stopped
    image: ghcr.io/google/cadvisor:v0.53.0
    volumes:
      - /:/rootfs:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    privileged: true
    environment:
      - DOCKER_HOST=tcp://docker-proxy:2375
    devices:
      - /dev/kmsg
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: 128M
    networks:
      - docker-proxy-net
    ports:
      - 8082:8080
    healthcheck:
      test: wget --spider http://localhost:8080/cadvisor/healthz || exit 1
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 20s
    depends_on:
      docker-proxy:
        condition: service_healthy

  vector:
    container_name: vector
    restart: unless-stopped
    image: timberio/vector:0.54.0-debian
    volumes:
      - ./vector.toml:/etc/vector/vector.toml:ro
    environment:
      - VECTOR_CONFIG=/etc/vector/vector.toml
      - AXIOM_TOKEN=${AXIOM_TOKEN}
      - AXIOM_DATASET_NAME=${AXIOM_DATASET_NAME}
      - AXIOM_REGION=${AXIOM_REGION}
    networks:
      - public-net
      - docker-proxy-net
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: 128M
    healthcheck:
      test: wget --spider http://localhost:8686/health || exit 1
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 20s
    depends_on:
      docker-proxy:
        condition: service_healthy
      cadvisor:
        condition: service_healthy
