[pytest]
addopts =
    --cov=./src
    --cov-branch
    --cov-fail-under=75
    --cov-report=html:cov_html
    --cov-report=term-missing
    --import-mode=importlib
    -v

norecursedirs =
    .*
    __pycache__
    htmlcov

python_files = test__*.py
testpaths = tests