[api]
enabled = true
address = "0.0.0.0:8686"

[sources.docker_logs]
type = "docker_logs"
docker_host = "tcp://docker-proxy:2375"

[sources.host_metrics]
type = "host_metrics"
scrape_interval_secs = 15

[sinks.axiom]
type = "axiom"
inputs = ["docker_logs, host_metrics"]
token = "${AXIOM_TOKEN}"
dataset = "${AXIOM_DATASET_NAME}"
region = "${AXIOM_REGION}"
