[api]
enabled = true
address = "0.0.0.0:8686"

[sources.docker_logs]
type = "docker_logs"
docker_host = "tcp://docker-proxy:2375"

[sources.host_metrics]
type = "host_metrics"
collectors = ["load"]
scrape_interval_secs = 15

[transforms.to_json]
type = "remap"
inputs = ["docker_logs"]
source = '''
parsed_message, err = parse_json(.message)


if err != null || !is_object(parsed_message){
    .vector_to_json_processed = false
    return .
}

.json_message = parsed_message
.vector_to_json_processed = true
del(.message)
'''

[sinks.axiom]
type = "axiom"
inputs = ["to_json", "host_metrics"]
token = "${AXIOM_TOKEN}"
dataset = "${AXIOM_DATASET_NAME}"
region = "${AXIOM_REGION}"
