name: App deploy
on: 
  workflow_dispatch:
    inputs:
      fastapi_scale:
        description: 'The number of api replication in docker'
        required: true
        default: 1
        type: number
      host:
        description: 'The ssh host'
        required: true
        type: string
      username:
        description: 'The ssh username'
        required: true
        type: string
      password:
        description: 'The ssh password'
        required: true
        type: string
      port:
        description: 'The ssh port'
        required: true
        default: 22
        type: number
      
jobs:
  deploy:
    permissions:
      packages: read
    runs-on: ubuntu-latest
    steps:
      - name: Deploy project over SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ inputs.host }}
          username: ${{ inputs.username }}
          password: ${{ inputs.password }}
          port: ${{ inputs.port }}
          script: |
            set -e

            echo "Step 1 : Retrieving code"
            cd ~/fastapi-template
            git pull

            echo "Step 2: Shutdown old docker container"
            docker compose --env-file .env.prod down

            echo "Step 3: Login to ghcr.io"
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login --username ${{ github.repository_owner }} --password-stdin ghcr.io

            echo "Step 4: Pull docker image"
            docker compose pull

            echo "Step 5: Logout of ghcr.io"
            docker logout ghcr.io
            rm ~/.docker/config.json

            echo "Step 6: Launching the containers"
            docker compose --env-file .env.prod up -d --scale fastapi=${{ inputs.fastapi_scale }}

            echo "Step 7: Cleanup history"
            history -c
            rm ~/.bash_history
