name: App deploy
on: 
  workflow_dispatch:
    inputs:
      fastapi_scale:
        description: 'The number of api replication in docker'
        required: true
        default: 1
        type: number
      env_file:
        description: 'The env file to load'
        required: true
        default: ".env.prod"
        type: string
      
jobs:
  deploy:
    permissions:
      packages: read
    runs-on: ubuntu-latest
    steps:
      - name: Deploy project over SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_IP }}
          port: ${{ secrets.VPS_PORT }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_KEY }}
          passphrase: ${{ secrets.VPS_PASSPHRASE }}
          script: |
            set -e

            echo "Step 1 : Retrieving code"
            cd ~/fastapi-template
            git pull

            echo "Step 2: Shutdown old docker container"
            docker compose --env-file .env.prod down --remove-orphans 

            echo "Step 3: Login to ghcr.io"
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login --username ${{ github.repository_owner }} --password-stdin ghcr.io

            echo "Step 4: Pull docker image"
            docker compose pull

            echo "Step 5: Logout of ghcr.io"
            docker logout ghcr.io
            rm ~/.docker/config.json

            echo "Step 6: Launching the containers"
            docker compose --env-file ${{ inputs.env_file }} up -d --scale fastapi=${{ inputs.fastapi_scale }}
